### ISSUE TITLE
Build fails due to API changes

### ISSUE THREAD

**Issue by vballoli** [tensorflow/swift-models#397]
The build fails while compiling `ResNet` and `ResNetv2` since `useBias: false` is used. By simply removing this argument, this should be fixed right ? I'd like to open a simple PR fix for this.

**Comment by Shashi456** [comment]
`useBias` by default is true. Removing the argument would make it true so I don't think that's desirable.

**Comment by vballoli** [comment]
Right now both the variants of `ResNet` use `Conv2D(filterShape:, strides:, padding:, )` as their initialize call, which has the default argument of `biasInitializer:zeros()`, so technically that's the equivalent of `useBias: false`, right ? @Shashi456

**Comment by vballoli** [comment]
I'm referring to this call: https://www.tensorflow.org/swift/api_docs/Structs/Conv2D#initfiltershape:strides:padding:dilations:activation:filterinitializer:biasinitializer:

**Comment by Shashi456** [comment]
@vballoli zeros just initializes the bias variable to a tensor of zeros.

**Comment by vballoli** [comment]
Oh yeah, I just realized it, my bad. Misread `bias != nil` for the initializer call. `useBias` was added later on by @sgugger. I guess a rebuild should fix it! Thanks a lot!! @Shashi456

**Comment by BradLarson** [comment]
I'll also point out that if you're seeing this in Colab, that's because we made this change in anticipation of Colab being updated with the 0.8 toolchain quickly. We hit a slight delay on that, but still expect the 0.8 toolchain to go live in Colab any day now. This API mismatch will be resolved in Colab once that happens. You can switch to the "tensorflow-0.7" branch of swift-models if you need to work in Colab before the new toolchain is live.
