### ISSUE TITLE
`ImagenetteBatchers` localStorageDirectory should be changed

### ISSUE THREAD

**Issue by Kshitij09** [tensorflow/swift-models#407]
Currently, `ImagenetteBatchers` download the dataset to default 'temporary' directory (/tmp in my case). The problem I'm facing is the downloaded dataset gets removed on every system reboot and hence the `Batchers` start re-downloading it.
```
Loading resource: imagenette-320
File does not exist locally at expected path: /tmp/Imagenette/imagenette-320 and must be fetched
Fetching URL: https://s3.amazonaws.com/fast-ai-imageclas/imagenette-320.tgz...
``` 

The workaround I did is to copy downloaded folder to some persistent path and copy it back to expected path by `ImagenetteBatchers` before using it.

**Comment by BradLarson** [comment]
The system temporary directory has been intentionally chosen as a default cache location because it's generally present on every system and is user-writable. This is intended as a cache, and not permanent storage, so it can be anticipated that it might be wiped on reboots.

The Imagenette and other datasets allow you to override this location using the `localStorageDirectory` parameter, and the download routines let you set a different target location. Alternatively, the Imagenette dataset's compressed archive can be stored locally and you can point to the local URL instead of the remote one as a download source. Those means allow you to override this behavior to point to a more permanent location on your specific local system, if desired.

The temporary directory is something that could be relied on to work out of the box across many systems and platforms, which is why it was chosen as the default.

**Comment by Kshitij09** [comment]
Got it! thanks for the clarification. :+1:
