### ISSUE TITLE
Batcher and Parallel Data Processing

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/swift-models#440]
What is the status of parallel data fetching and preprocessing with the batcher API? I noticed that there is a concurrent map implementation but couldn't find much else. I previously implemented a version of a prefetching iterator [here](https://github.com/eaplatanios/nca/blob/master/Sources/NCA/Utilities/Data.swift) but I'm not sure if that functionality is covered in batcher currently. If not, should I look into opening a PR when I get a chance or is there something already being implemented?

**Comment by sgugger** [comment]
The `Batcher` is using parallelism to grab the samples from the dataset you give it and batch them (with that `concurrentMap` you mention). This is a work in progress and the final design of `Batcher` is going to be ready soon so I'd hold off any PR for now and check the parallelism on that final design.

**Comment by eaplatanios** [comment]
Cool, thanks for the response @sgugger! :)

**Comment by saeta** [comment]
(Closing issue; feel free to re-open.)

**Comment by xanderdunn** [comment]
I was looking for parallel data processing and prefetching of batch data because waiting on each batch to be generated is a considerable portion of runtime for my model. Tensorflow has a nice set of APIs for doing this [here](https://www.tensorflow.org/guide/data_performance#prefetching). 

It looks like `Batcher` no longer exists. It was perhaps moved to swift-apis and renamed to `TrainingEpochs` [here](https://github.com/tensorflow/swift-apis/blob/b7148bc6f5e76bd55e5b11ebd5dd14e42c6ef5a3/Sources/TensorFlow/Epochs/TrainingEpochs.swift)? 

I found @eaplatanios introduced a `PrefetchIterator` [here](https://github.com/tensorflow/swift-models/blame/d9a126df65c406239a2a4922bd6ae8460679d693/Datasets/CoLA/DataUtilities.swift#L228) in pull request #231 that accomplished this goal with the BERT CoLA training dataset, but it has since been removed. I don't see a similar functionality in swift-apis.

Is swift-apis now the appropriate place to open an issue for this?

**Comment by BradLarson** [comment]
@xanderdunn - Batcher became [Epochs](https://github.com/tensorflow/swift-apis/tree/main/Sources/TensorFlow/Epochs), taking the lessons learned from Batcher and making them more extensible. Parallel data processing fits within the Epochs model, and the TextUnsupervised.swift file for loading the WikiText variants shows [one application of that](https://github.com/tensorflow/swift-models/blob/main/Datasets/TextUnsupervised/TextUnsupervised.swift#L222). Prefetching should also be supported, although I don't know if we have any helpers around that.

**Comment by xanderdunn** [comment]
Thanks @BradLarson!  The `TrainingEpochs` you linked to is what our project is currently using. It looks like the WikiText dataset uses `concurrentMap` for the one time initial encoding of the dataset when it's first read from CSV, but I don't see any concurrency in the [continuous generation of batches](https://github.com/tensorflow/swift-models/blob/main/Datasets/TextUnsupervised/TextUnsupervised.swift#L122). However, it's straightforward to introduce concurrency into the maps that are occurring inside TrainingEpochs. The only challenge is sorting out the non-thread-safe random number generators. Do you know of any code samples that manage random number generation across threads?

I think the prefetch functionality is the only thing missing. @eaplatanios's `PrefetchIterator` may be a drop-in tool for prefetching values from `TrainingEpochs`.

**Comment by BradLarson** [comment]
@xanderdunn - I don't think we have a method yet of handling a seeded random number generator deterministically across batching (I think that I created issue #425 to track the addition of this), but I could be wrong. There might be a way to do this with Epochs that became part of the API after I created the above in the Batcher days.
