### ISSUE TITLE
How to get text output from Language models

### ISSUE THREAD

**Issue by porterchild** [tensorflow/swift-models#502]
I'm struggling to get text output from BERT given a prompt. Looking through the code I've understood that the flow for inference should be something like this:

```
let bertPretrained = BERT.PreTrainedModel.bertBase(cased: false, multilingual: false)
let workspaceURL = URL(fileURLWithPath: "bert_models", isDirectory: true,
                       relativeTo: URL(fileURLWithPath: NSTemporaryDirectory(),
                                       isDirectory: true))
let bert = try BERT.PreTrainedModel.load(bertPretrained)(from: workspaceURL)

let input = "The quick brown fox " //feed this to the model and see what it thinks comes next

let batch = bert.preprocess(sequences: [input])

let rawOutput = bert(batch)

//TODO: 
// de-embed rawOutput? or is it called de-coding?

//de tokenize - reverse whatever bert.tokerizer.tokenize does, I guess
```

Some help getting from `rawOutput` to a `String` would be much appreciated.

Thanks!

**Comment by xihui-wu** [comment]
BERT is a general-purpose "language understanding" model. It doesn't have text output. The output of it is nothing but a logical representation of the input text in form of a vector of hidden_size. It's usually used for downstream NLP tasks by attaching extra layers on top of it. In our example here we attach a classifier to execute a classification task which classifies if the input sentence is grammarly legit or not.

Back to you problem, can I ask what NLP task are you running ? If it is the classification task as we do, the output from BERT is nothing but tensors and final output from the classifier is 0 or 1.

Since in the title you mentioned "get text output from Language models", I can speak of GPT2 for your information. This model does language generation and have text output. So inputting a sentence will output a most likely next sentence. See [here](https://github.com/tensorflow/swift-models/blob/master/Examples/GPT2-Inference/main.swift).

**Comment by porterchild** [comment]
Thanks for the explanation, I wasn't sure BERT and GPT-2 were usable in the same ways, and you confirmed that for me. I've used GPT-2 for generation and was hoping I could use Albert as a more lightweight way to do it, but it looks like the models are not totally analogous in their abilities. Thanks, I'll go back to GPT-2!
