### ISSUE TITLE
Executable products (in tensorflow/swift-models) conflicting with modules (of same name) on local Swift package

### ISSUE THREAD

**Issue by rahulbhalley** [tensorflow/swift-models#561]
Currently, [tensorflow/swift-models](https://github.com/tensorflow/swift-models) repository contains:
1. datasets *and*
2. models 

Akin to [tensorflow/swift-apis](https://github.com/tensorflow/swift-apis) (which implements basic building blocks for constructing and training ML models), wouldn't it be more appropriate to split [tensorflow/swift-models](https://github.com/tensorflow/swift-models) into:
1. tensorflow/swift-datasets (consisting of only datasets) and
2. tensorflow/swift-models (consisting of only models and using tensorflow/swift-datasets as package dependency)? 

Any plans in this direction?

The problem I have right now is that I want to get only datasets to use for training my GAN defined as module in my SPM in Xcode (I cannot rename it). When I add [tensorflow/swift-models](https://github.com/tensorflow/swift-models) as dependency the GAN module (in [tensorflow/swift-models](https://github.com/tensorflow/swift-models)) start conflicting with my GAN module. Moreover, I don't need any models but datasets.

**Comment by BradLarson** [comment]
As it is, we know that the number of repositories associated with the project [can cause some confusion](https://groups.google.com/a/tensorflow.org/d/msg/swift/95rP1GyN26I/_2jJYcJfAQAJ), so I think our tendency would be to work to reduce the number of those. There are also logistical challenges with opening and maintaining another repository.

The problem you're encountering might be due to the fact that we're currently vending most of the executable targets from within Package.swift, when we probably shouldn't be doing so. In your specific case, my guess is that by removing [this line](https://github.com/tensorflow/swift-models/blob/master/Package.swift#L27) you'd no longer see a conflict in your project. You could try that out with a local copy of swift-models (referenced as a local package) and see if that works. If so, we can strip out the executable targets to prevent future conflicts like this.

**Comment by rahulbhalley** [comment]
Wow. That just worked like magic! Thank you so much @BradLarson. 😊 

May I create a PR to remove executables?

**Comment by BradLarson** [comment]
If you want to remove all the `.executable` products (while leaving the targets alone), please do. Otherwise, I can take care of it.

**Comment by rahulbhalley** [comment]
@BradLarson please review the PR https://github.com/tensorflow/swift-models/pull/572

**Comment by BradLarson** [comment]
Robustly resolved via PR #572.
