### ISSUE TITLE
Autoencoder example uses deprecated API and doesn't compile anymore

### ISSUE THREAD

**Issue by valeriyvan** [tensorflow/swift-models#93]

**Comment by rxwei** [comment]
[TF-193](https://bugs.swift.org/browse/TF-193) is the ongoing issue. If you are interested, you are welcome to join the effort! We plan to move swift-models to a SwiftPM package. This is blocked by the fact that the autoencoder example is not using the latest high-level APIs yet.

If you are interested and start to make progress, please send a reply here and to the JIRA bug. The changes should be committed to the `master` branch instead of the `stable` branch. Thanks!
